### ISSUE TITLE
OSError when using multiple async feed_batch() instead of feed_data_point()

### ISSUE THREAD

**Issue by WhiteH4tDude** [vespa-engine/pyvespa#476]
I'm feeding Vespa with entities from my database as quick as possible, using a coroutine for each entity type (10 entities at total). To feed vespa, I'm using `feed_batch` method. But after some time, the following error is raised:

```
Traceback (most recent call last):
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1070, in create_connection
    raise exceptions[0]
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1054, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 963, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\jeanl\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 608, in finish_connect
    ov.getresult()
OSError: [WinError 52] Você não foi conectado porque existe um nome duplicado na rede. Se estiver ingressando em um domínio, vá para Sistema no Painel de Controle para alterar o nome do computador e tente novamente. Se estiver ingressando em um grupo de trabalho, escolha outro nome de grupo de trabalho

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\vespa\application.py", line 1046, in feed_data_point
    response = await self.aiohttp_session.post(end_point, json=vespa_format)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 1200, in _create_direct_connection
    raise last_exc
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 1169, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Você não foi conectado porque existe um nome duplicado na rede. Se estiver ingressando em um domínio, vá para Sistema no Painel de Controle para alterar o nome do computador e tente novamente. Se estiver ingressando em um grupo de trabalho, escolha outro nome de grupo de trabalho]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\vespa\application.py", line 1066, in _feed_data_point_semaphore
    return await self.feed_data_point(
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\jeanl\AppData\Local\pypoetry\Cache\virtualenvs\atena-1t8xRFjC-py3.10\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25edfc98610 state=finished raised ClientConnectorError>]
```

The only thing I'm doing is something like this:

```
async feeder(database_session, entity_type):
    while is_running:
        entities = await database_session.scalars(entity_type.query.limit(100))  # Get data from Db using SQLA

        batch = entities_to_json(entities)

        response = vespa_application.feed_batch(
            batch=batch, schema=entity_type.schema_name, output=False       # Feed vespa with 100 entities
        )

async main():
    coros = list()

    for entity_type in entity_types:  # 10 coroutines
        coros.append(feeder(create_new_async_session(), entity_type))

    await asyncio.gather(*coros)

asyncio.run(main)
```

This error won't happen if I use `feed_data_point` inside a for-loop instead of `feed_batch`.

**Comment by maxice8** [comment]
The Error message is in Brazilian Portuguese, here is the equivalent in English:

```text
You were not connected because a duplicate name exists on the network. If joining a domain, go to System in Control Panel to change the computer name and try again. If joining a workgroup choose another workgroup name.
```

**Comment by jobergum** [comment]
I'm resolving this based on the above, we are also deprecating the batch api's (see https://github.com/vespa-engine/pyvespa/issues/600)
