### ISSUE TITLE
Improve error handling on 5xx-error with async-client

### ISSUE THREAD

**Issue by thomasht86** [vespa-engine/pyvespa#926]
If 3 retries fails, user may get:

```python
failed: RetryError(<Future at
 0xfffe30231510 state=finished raised JSONDecodeError>)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vespa/application.py", line 1538, in query
    json=r.json(), status_code=r.status_code, url=str(r.url)
         ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

which is not very helpful. 

Better to check response code first and raise error on 5xx, rather than offloading the error raising to the JSON-decoder.

**Comment by thomasht86** [comment]
[This test ](https://github.com/vespa-engine/pyvespa/actions/runs/11009187660/job/30569145128) also fails intermittently

```
FAILED tests/integration/test_integration_vespa_cloud.py::TestMsmarcoApplication::test_execute_async_data_operations - urllib3.exceptions.HTTPError: HTTP 502 error: Bad Gateway for /application/v4/tenant/vespa-team/application/pyvespa-integration/instance/msmarco/job/dev-aws-us-east-1c/run/1?after=39
```

**Comment by thomasht86** [comment]
This was improved in #1013 and is no longer a significant issue
